
// Code generated by stanc v2.29.0
#include <stan/model/model_header.hpp>
namespace model1_fit_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 46> locations_array__ = 
{" (found before start of program)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 20, column 2 to column 17)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 23, column 2 to column 28)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 24, column 2 to column 27)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 25, column 2 to column 32)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 26, column 2 to column 29)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 27, column 2 to column 25)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 28, column 2 to column 27)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 29, column 2 to column 24)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 55, column 2 to column 16)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 56, column 2 to column 18)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 58, column 4 to line 64, column 62)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 67, column 4 to line 73, column 61)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 57, column 17 to line 74, column 3)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 57, column 2 to line 74, column 3)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 34, column 2 to column 19)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 35, column 2 to column 32)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 36, column 2 to column 31)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 37, column 2 to column 37)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 38, column 2 to column 33)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 39, column 2 to column 35)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 40, column 2 to column 37)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 41, column 2 to column 34)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 45, column 4 to line 51, column 66)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 44, column 2 to line 51, column 66)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 3, column 2 to column 17)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 6, column 2 to column 8)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 7, column 8 to column 9)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 7, column 2 to column 11)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 10, column 16 to column 17)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 10, column 2 to column 19)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 11, column 15 to column 16)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 11, column 2 to column 18)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 12, column 21 to column 22)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 12, column 2 to column 24)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 13, column 17 to column 18)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 13, column 2 to column 20)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 14, column 20 to column 21)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 14, column 2 to column 23)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 15, column 21 to column 22)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 15, column 2 to column 24)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 16, column 18 to column 19)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 16, column 2 to column 21)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 20, column 10 to column 13)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 55, column 13 to column 14)",
 " (in '/home/DA_final_project/stan_files/model1_fit.stan', line 56, column 15 to column 16)"};




class model1_fit_model final : public model_base_crtp<model1_fit_model> {

 private:
  int N;
  int K;
  std::vector<int> y;
  std::vector<int> neigh_sat;
  std::vector<int> hous_sat;
  std::vector<int> com_even_avail;
  std::vector<int> sen_of_sec;
  std::vector<double> ann_hous_inc;
  std::vector<int> liv_with_child;
  std::vector<int> is_disabled;
  int c_1dim__; 
  
 
 public:
  ~model1_fit_model() { }
  
  inline std::string model_name() const final { return "model1_fit_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.0", "stancflags = "};
  }
  
  
  model1_fit_model(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "model1_fit_model_namespace::model1_fit_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 25;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 25;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 26;
      context__.validate_dims("data initialization","K","int",
           std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      
      
      current_statement__ = 26;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 27;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 28;
      context__.validate_dims("data initialization","y","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 28;
      y = context__.vals_i("y");
      current_statement__ = 29;
      stan::math::validate_non_negative_index("neigh_sat", "N", N);
      current_statement__ = 30;
      context__.validate_dims("data initialization","neigh_sat","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      neigh_sat = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 30;
      neigh_sat = context__.vals_i("neigh_sat");
      current_statement__ = 31;
      stan::math::validate_non_negative_index("hous_sat", "N", N);
      current_statement__ = 32;
      context__.validate_dims("data initialization","hous_sat","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      hous_sat = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 32;
      hous_sat = context__.vals_i("hous_sat");
      current_statement__ = 33;
      stan::math::validate_non_negative_index("com_even_avail", "N", N);
      current_statement__ = 34;
      context__.validate_dims("data initialization","com_even_avail","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      com_even_avail = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 34;
      com_even_avail = context__.vals_i("com_even_avail");
      current_statement__ = 35;
      stan::math::validate_non_negative_index("sen_of_sec", "N", N);
      current_statement__ = 36;
      context__.validate_dims("data initialization","sen_of_sec","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      sen_of_sec = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 36;
      sen_of_sec = context__.vals_i("sen_of_sec");
      current_statement__ = 37;
      stan::math::validate_non_negative_index("ann_hous_inc", "N", N);
      current_statement__ = 38;
      context__.validate_dims("data initialization","ann_hous_inc","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      ann_hous_inc = 
        std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 38;
      ann_hous_inc = context__.vals_r("ann_hous_inc");
      current_statement__ = 39;
      stan::math::validate_non_negative_index("liv_with_child", "N", N);
      current_statement__ = 40;
      context__.validate_dims("data initialization","liv_with_child","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      liv_with_child = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 40;
      liv_with_child = context__.vals_i("liv_with_child");
      current_statement__ = 41;
      stan::math::validate_non_negative_index("is_disabled", "N", N);
      current_statement__ = 42;
      context__.validate_dims("data initialization","is_disabled","int",
           std::vector<size_t>{static_cast<size_t>(N)});
      is_disabled = std::vector<int>(N, std::numeric_limits<int>::min());
      
      
      current_statement__ = 42;
      is_disabled = context__.vals_i("is_disabled");
      current_statement__ = 43;
      c_1dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 43;
      c_1dim__ = (K - 1);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("c", "K - 1", c_1dim__);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("happy", "N", N);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = c_1dim__ + 10 + 10 + 5 + 10 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model1_fit_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, 1> c =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(c_1dim__,
           DUMMY_VAR__);
      current_statement__ = 1;
      c = in__.template read_constrain_ordered<
            Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(lp__,
            c_1dim__);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_neigh_sat =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(10, DUMMY_VAR__);
      current_statement__ = 2;
      coef_neigh_sat = in__.template read<
                         Eigen::Matrix<local_scalar_t__, -1, 1>>(10);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_hous_sat =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(10, DUMMY_VAR__);
      current_statement__ = 3;
      coef_hous_sat = in__.template read<
                        Eigen::Matrix<local_scalar_t__, -1, 1>>(10);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_com_even_avail =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(5, DUMMY_VAR__);
      current_statement__ = 4;
      coef_com_even_avail = in__.template read<
                              Eigen::Matrix<local_scalar_t__, -1, 1>>(5);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_sen_of_sec =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(10, DUMMY_VAR__);
      current_statement__ = 5;
      coef_sen_of_sec = in__.template read<
                          Eigen::Matrix<local_scalar_t__, -1, 1>>(10);
      local_scalar_t__ coef_ann_hous_inc = DUMMY_VAR__;
      current_statement__ = 6;
      coef_ann_hous_inc = in__.template read<local_scalar_t__>();
      local_scalar_t__ coef_liv_with_child = DUMMY_VAR__;
      current_statement__ = 7;
      coef_liv_with_child = in__.template read<local_scalar_t__>();
      local_scalar_t__ coef_is_disabled = DUMMY_VAR__;
      current_statement__ = 8;
      coef_is_disabled = in__.template read<local_scalar_t__>();
      {
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(c, 0, 3));
        current_statement__ = 16;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(coef_neigh_sat, 0, 1));
        current_statement__ = 17;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(coef_hous_sat, 0, 1));
        current_statement__ = 18;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(coef_com_even_avail, 0, 1));
        current_statement__ = 19;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(coef_sen_of_sec, 0, 1));
        current_statement__ = 20;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(coef_ann_hous_inc, 0, 1));
        current_statement__ = 21;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(coef_liv_with_child, 0, 1));
        current_statement__ = 22;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(coef_is_disabled, 0, 1));
        current_statement__ = 24;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 23;
          lp_accum__.add(
            stan::math::ordered_logistic_lpmf<propto__>(
              stan::model::rvalue(y, "y", stan::model::index_uni(n)),
              ((((((stan::model::rvalue(coef_neigh_sat, "coef_neigh_sat",
                      stan::model::index_uni(stan::model::rvalue(neigh_sat,
                                               "neigh_sat",
                                               stan::model::index_uni(n)))) +
                     stan::model::rvalue(coef_hous_sat, "coef_hous_sat",
                       stan::model::index_uni(stan::model::rvalue(hous_sat,
                                                "hous_sat",
                                                stan::model::index_uni(n)))))
                    +
                    stan::model::rvalue(coef_com_even_avail,
                      "coef_com_even_avail",
                      stan::model::index_uni(stan::model::rvalue(
                                               com_even_avail,
                                               "com_even_avail",
                                               stan::model::index_uni(n)))))
                   +
                   stan::model::rvalue(coef_sen_of_sec, "coef_sen_of_sec",
                     stan::model::index_uni(stan::model::rvalue(sen_of_sec,
                                              "sen_of_sec",
                                              stan::model::index_uni(n))))) +
                  (coef_ann_hous_inc *
                    stan::model::rvalue(ann_hous_inc, "ann_hous_inc",
                      stan::model::index_uni(n)))) +
                 (coef_liv_with_child *
                   stan::model::rvalue(liv_with_child, "liv_with_child",
                     stan::model::index_uni(n)))) +
                (coef_is_disabled *
                  stan::model::rvalue(is_disabled, "is_disabled",
                    stan::model::index_uni(n)))), c));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model1_fit_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, 1> c =
         Eigen::Matrix<double, -1, 1>::Constant(c_1dim__,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      c = in__.template read_constrain_ordered<
            Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(lp__,
            c_1dim__);
      Eigen::Matrix<double, -1, 1> coef_neigh_sat =
         Eigen::Matrix<double, -1, 1>::Constant(10,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      coef_neigh_sat = in__.template read<
                         Eigen::Matrix<local_scalar_t__, -1, 1>>(10);
      Eigen::Matrix<double, -1, 1> coef_hous_sat =
         Eigen::Matrix<double, -1, 1>::Constant(10,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      coef_hous_sat = in__.template read<
                        Eigen::Matrix<local_scalar_t__, -1, 1>>(10);
      Eigen::Matrix<double, -1, 1> coef_com_even_avail =
         Eigen::Matrix<double, -1, 1>::Constant(5,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      coef_com_even_avail = in__.template read<
                              Eigen::Matrix<local_scalar_t__, -1, 1>>(5);
      Eigen::Matrix<double, -1, 1> coef_sen_of_sec =
         Eigen::Matrix<double, -1, 1>::Constant(10,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      coef_sen_of_sec = in__.template read<
                          Eigen::Matrix<local_scalar_t__, -1, 1>>(10);
      double coef_ann_hous_inc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      coef_ann_hous_inc = in__.template read<local_scalar_t__>();
      double coef_liv_with_child = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      coef_liv_with_child = in__.template read<local_scalar_t__>();
      double coef_is_disabled = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      coef_is_disabled = in__.template read<local_scalar_t__>();
      out__.write(c);
      out__.write(coef_neigh_sat);
      out__.write(coef_hous_sat);
      out__.write(coef_com_even_avail);
      out__.write(coef_sen_of_sec);
      out__.write(coef_ann_hous_inc);
      out__.write(coef_liv_with_child);
      out__.write(coef_is_disabled);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<double> happy =
         std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      std::vector<double> log_lik =
         std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 14;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 11;
        stan::model::assign(happy,
          stan::math::ordered_logistic_rng(
            ((((((stan::model::rvalue(coef_neigh_sat, "coef_neigh_sat",
                    stan::model::index_uni(stan::model::rvalue(neigh_sat,
                                             "neigh_sat",
                                             stan::model::index_uni(n)))) +
                   stan::model::rvalue(coef_hous_sat, "coef_hous_sat",
                     stan::model::index_uni(stan::model::rvalue(hous_sat,
                                              "hous_sat",
                                              stan::model::index_uni(n))))) +
                  stan::model::rvalue(coef_com_even_avail,
                    "coef_com_even_avail",
                    stan::model::index_uni(stan::model::rvalue(
                                             com_even_avail,
                                             "com_even_avail",
                                             stan::model::index_uni(n))))) +
                 stan::model::rvalue(coef_sen_of_sec, "coef_sen_of_sec",
                   stan::model::index_uni(stan::model::rvalue(sen_of_sec,
                                            "sen_of_sec",
                                            stan::model::index_uni(n))))) +
                (coef_ann_hous_inc *
                  stan::model::rvalue(ann_hous_inc, "ann_hous_inc",
                    stan::model::index_uni(n)))) +
               (coef_liv_with_child *
                 stan::model::rvalue(liv_with_child, "liv_with_child",
                   stan::model::index_uni(n)))) +
              (coef_is_disabled *
                stan::model::rvalue(is_disabled, "is_disabled",
                  stan::model::index_uni(n)))), c, base_rng__),
          "assigning variable happy", stan::model::index_uni(n));
        current_statement__ = 12;
        stan::model::assign(log_lik,
          stan::math::ordered_logistic_lpmf<false>(
            stan::model::rvalue(y, "y", stan::model::index_uni(n)),
            ((((((stan::model::rvalue(coef_neigh_sat, "coef_neigh_sat",
                    stan::model::index_uni(stan::model::rvalue(neigh_sat,
                                             "neigh_sat",
                                             stan::model::index_uni(n)))) +
                   stan::model::rvalue(coef_hous_sat, "coef_hous_sat",
                     stan::model::index_uni(stan::model::rvalue(hous_sat,
                                              "hous_sat",
                                              stan::model::index_uni(n))))) +
                  stan::model::rvalue(coef_com_even_avail,
                    "coef_com_even_avail",
                    stan::model::index_uni(stan::model::rvalue(
                                             com_even_avail,
                                             "com_even_avail",
                                             stan::model::index_uni(n))))) +
                 stan::model::rvalue(coef_sen_of_sec, "coef_sen_of_sec",
                   stan::model::index_uni(stan::model::rvalue(sen_of_sec,
                                            "sen_of_sec",
                                            stan::model::index_uni(n))))) +
                (coef_ann_hous_inc *
                  stan::model::rvalue(ann_hous_inc, "ann_hous_inc",
                    stan::model::index_uni(n)))) +
               (coef_liv_with_child *
                 stan::model::rvalue(liv_with_child, "liv_with_child",
                   stan::model::index_uni(n)))) +
              (coef_is_disabled *
                stan::model::rvalue(is_disabled, "is_disabled",
                  stan::model::index_uni(n)))), c),
          "assigning variable log_lik", stan::model::index_uni(n));
      }
      out__.write(happy);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__, -1, 1> c =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(c_1dim__,
           DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= c_1dim__; ++sym1__) {
        stan::model::assign(c, in__.read<local_scalar_t__>(),
          "assigning variable c", stan::model::index_uni(sym1__));
      }
      out__.write_free_ordered(c);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_neigh_sat =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(10, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
        stan::model::assign(coef_neigh_sat, in__.read<local_scalar_t__>(),
          "assigning variable coef_neigh_sat", stan::model::index_uni(sym1__));
      }
      out__.write(coef_neigh_sat);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_hous_sat =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(10, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
        stan::model::assign(coef_hous_sat, in__.read<local_scalar_t__>(),
          "assigning variable coef_hous_sat", stan::model::index_uni(sym1__));
      }
      out__.write(coef_hous_sat);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_com_even_avail =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(5, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= 5; ++sym1__) {
        stan::model::assign(coef_com_even_avail,
          in__.read<local_scalar_t__>(),
          "assigning variable coef_com_even_avail", stan::model::index_uni(sym1__));
      }
      out__.write(coef_com_even_avail);
      Eigen::Matrix<local_scalar_t__, -1, 1> coef_sen_of_sec =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(10, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
        stan::model::assign(coef_sen_of_sec, in__.read<local_scalar_t__>(),
          "assigning variable coef_sen_of_sec", stan::model::index_uni(sym1__));
      }
      out__.write(coef_sen_of_sec);
      local_scalar_t__ coef_ann_hous_inc = DUMMY_VAR__;
      coef_ann_hous_inc = in__.read<local_scalar_t__>();
      out__.write(coef_ann_hous_inc);
      local_scalar_t__ coef_liv_with_child = DUMMY_VAR__;
      coef_liv_with_child = in__.read<local_scalar_t__>();
      out__.write(coef_liv_with_child);
      local_scalar_t__ coef_is_disabled = DUMMY_VAR__;
      coef_is_disabled = in__.read<local_scalar_t__>();
      out__.write(coef_is_disabled);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"c", "coef_neigh_sat",
      "coef_hous_sat", "coef_com_even_avail", "coef_sen_of_sec",
      "coef_ann_hous_inc", "coef_liv_with_child", "coef_is_disabled",
      "happy", "log_lik"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{
                                                                   static_cast<size_t>(c_1dim__)
                                                                   },
      std::vector<size_t>{static_cast<size_t>(10)},
      std::vector<size_t>{static_cast<size_t>(10)},
      std::vector<size_t>{static_cast<size_t>(5)},
      std::vector<size_t>{static_cast<size_t>(10)}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= c_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "c" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_neigh_sat" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_hous_sat" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 5; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_com_even_avail" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_sen_of_sec" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "coef_ann_hous_inc");
    param_names__.emplace_back(std::string() + "coef_liv_with_child");
    param_names__.emplace_back(std::string() + "coef_is_disabled");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "happy" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= c_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "c" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_neigh_sat" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_hous_sat" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 5; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_com_even_avail" + '.' + std::to_string(sym1__));
      } 
    }
    for (int sym1__ = 1; sym1__ <= 10; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "coef_sen_of_sec" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "coef_ann_hous_inc");
    param_names__.emplace_back(std::string() + "coef_liv_with_child");
    param_names__.emplace_back(std::string() + "coef_is_disabled");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "happy" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"c\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(c_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"coef_neigh_sat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(10) + "},\"block\":\"parameters\"},{\"name\":\"coef_hous_sat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(10) + "},\"block\":\"parameters\"},{\"name\":\"coef_com_even_avail\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(5) + "},\"block\":\"parameters\"},{\"name\":\"coef_sen_of_sec\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(10) + "},\"block\":\"parameters\"},{\"name\":\"coef_ann_hous_inc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"coef_liv_with_child\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"coef_is_disabled\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"happy\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"c\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(c_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"coef_neigh_sat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(10) + "},\"block\":\"parameters\"},{\"name\":\"coef_hous_sat\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(10) + "},\"block\":\"parameters\"},{\"name\":\"coef_com_even_avail\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(5) + "},\"block\":\"parameters\"},{\"name\":\"coef_sen_of_sec\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(10) + "},\"block\":\"parameters\"},{\"name\":\"coef_ann_hous_inc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"coef_liv_with_child\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"coef_is_disabled\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"happy\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((((c_1dim__ + 10) + 10) + 5) + 10) + 1) + 1) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (N + N);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((((c_1dim__ + 10) + 10) + 5) + 10) + 1) + 1) + 1);
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (N + N);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 8> names__{"c", "coef_neigh_sat",
      "coef_hous_sat", "coef_com_even_avail", "coef_sen_of_sec",
      "coef_ann_hous_inc", "coef_liv_with_child", "coef_is_disabled"};
      const std::array<Eigen::Index, 8> constrain_param_sizes__{c_1dim__, 
       10, 10, 5, 10, 1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = model1_fit_model_namespace::model1_fit_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return model1_fit_model_namespace::profiles__;
}

#endif


